### ISSUE TITLE
How to include extensions / themes for aldeed:autoform?

### ISSUE THREAD

**Issue by jankapunkt** [arggh/awesome-blaze#2]
AutoForm is a very big an famouse package and it lives by it's extension and theming system.

Unfortunately the list of extensions and themes in the package is not maintained, some of them are abandoned or replaced by others. New extensions are not added an so on.

Maybe it makes sense to make AutoForm an own category?

**Comment by arggh** [comment]
Good idea. I don't use it myself, but I know a lot of Meteor devs do. AutoForm definitely warrants it's own category. What do you think, should we keep AutoForm package inside it's current category and only add the the extensions under the new category, or wrap everything together in the new AutoForm category?

**Comment by jankapunkt** [comment]
I suggest to wrap it all up under an own category and have some sub categories for extensions and themes:

Example 1 using one-depth of bullets: 
<hr>

## AutoForm

* [aldeed:autoform]() - (main package) UI components and helpers to easily create basic forms with automatic insert and update events, and automatic reactive validation. [Badge here]

### Extensions

* [someone:autoform-extension-xyz]() - description [optionalbadge]

### Themes 

* [someone:autoform-theme-xyz]() - description [optionalbadge]

<hr>

Example 2 using two-depth of bullets: 
<hr>

## AutoForm

* [aldeed:autoform]() - (main package) UI components and helpers to easily create basic forms with automatic insert and update events, and automatic reactive validation. [Badge here]

* ### Extensions

  * [someone:autoform-extension-xyz]() - description [optionalbadge]

* ### Themes 

  * [someone:autoform-theme-xyz]() - description [optionalbadge]
<hr>

For extensions we could also use some finer grained sub-categorization as they already did in the original package. However that would also add lots of text to the doc and maybe making it unnecessarily complex.

**Comment by arggh** [comment]
Out of curiosity, how many extensions or themes are we talking about that should/would be listed?

I'm thinking it might better to introduce a new subcategory for `Blaze packages` called `Forms`, and inside that subcategory we could have an entry for `aldeed:autoform`, and below possibly it's extensions and themes:

# Blaze packages

### Forms
- [aldeed:autoform](https://) - UI components and helpers to easily create basic forms with automatic insert and update events, and automatic reactive validation.
  - #### Extensions
     - [someone:autoform-extension-xyz](https://) - description
     - [someone:autoform-extension-xyz](https://) - description
     - [someone:autoform-extension-xyz](https://) - description
     - [someone:autoform-extension-xyz](https://) - description
  - #### Themes
     - [someone:autoform-theme-xyz](https://) - description
     - [someone:autoform-theme-xyz](https://) - description
     - [someone:autoform-theme-xyz](https://) - description
- [templates:forms](https://) - Build production-ready, reactive forms in minutes. Even complex workflows can be achieved with just a few lines of code.

------

What do you think?

**Comment by jankapunkt** [comment]
Makes sense since AutoForm is not the only form related package.

**Comment by arggh** [comment]
Would you like to tackle this? Maybe include AutoForm extensions and themes you already know to be of high quality?

**Comment by jankapunkt** [comment]
Yes I will create a PR soon.

**Comment by jankapunkt** [comment]
@arggh I found that many of the packages listed in the AutoForm doc are not maintained anymore.

Does it make snese to skip them and only include maintained packages here?

**Comment by arggh** [comment]
Given the situation with Blaze in general, my idea was to include only packages that are maintained, _unless_ the package meets the following criteria

1. It's popular enough, meaning it's useful
2. It's stable and "just works"

A lots of Blaze packages don't really need that much maintenance, as Blaze itself has (almost) entirely stopped evolving, at least for now.

For these cases, I've included the ![Not maintained](https://img.shields.io/badge/Maintained%3F-no-red.svg) -badge

```
 ![Not maintained](https://img.shields.io/badge/Maintained%3F-no-red.svg)
```

I'd still like to avoid dumping all the packages in Atmosphere to this list by filtering the mediocre ones away.
